### ISSUE TITLE
Import database of other auth plugins

### ISSUE THREAD

**Issue by Matthww** [PEMapModder/HereAuth#1]

**Comment by PEMapModder** [comment]
No, but the hash is compatible, so it will be easy to port .

**Comment by PEMapModder** [comment]
For auth plugins other than SimpleAuth, if they use a different hash algo, I will do it with a login-to-import style, where while importing, the old hash will be stored, and when the player logins, the plugin will verify if the old hash algo matches, and if yes, store the compatible hash and delete the old hash.

**Comment by PEMapModder** [comment]
Going to add /import soon.

**Comment by Matthww** [comment]
If this is ready for use and you can make that importing work. I will use this!

**Comment by PEMapModder** [comment]
What kinds of database would people probably import from?
Only SimpleAuth and ServerAuth?

**Comment by Matthww** [comment]
I think SimpleAuth but due to SimpleAuth having problems with the new PocketMine I think many people use ServerAuth.

I use SimpleAuth because I can't switch.

**Comment by PEMapModder** [comment]
Yes, but no any other auth plugins are popularly used, right?

**Comment by Matthww** [comment]
I think so

**Comment by Matthww** [comment]
http://stats.pocketmine.net/plugins

**Comment by Matthww** [comment]
https://gyazo.com/fd859c00f2d6be6202ed67ea7ab3011c

**Comment by 64FF00** [comment]
1337

**Comment by robske110** [comment]
SimpleAuth fully works with the ^new^ pocketmine!

**Comment by Lucario2** [comment]
...

**Comment by AndreyNazarchuk** [comment]
So is this done yet?

**Comment by PEMapModder** [comment]
No, don't have time

**Comment by AndreyNazarchuk** [comment]
Ah, OK.

**Comment by robske110** [comment]
Erm
SimpleAuth has no problems

**Comment by PEMapModder** [comment]
Added.

**Comment by XiangZhao969** [comment]
How to import?

**Comment by PEMapModder** [comment]
Use the `/import` command.
