### ISSUE TITLE
inventory

### ISSUE THREAD

**Issue by MaryVictoria** [PEMapModder/HereAuth#12]
inventory bug... after i give player invetory nothing   ...

**Comment by PEMapModder** [comment]
1. Is the player logged in/registered?
2. Did you enable/disable inventory masking?

**Comment by MaryVictoria** [comment]
is its reg. i try it to my self.

**Comment by PEMapModder** [comment]
@MaryVictoria I am unable to reproduce the bug.
Remember that HereAuth has inventory masking, where the player inventory is shown as empty until he has logged in/registered.
