### ISSUE TITLE
CreeperLewisAuth #BETTER

### ISSUE THREAD

**Issue by CreeperLewisUK** [PEMapModder/HereAuth#18]
# TWEET ME SO I CAN GIVE U MY BEST AUTH NOT LIKE THIS SHITTY ONE LIKE LEET

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

V'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.
'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

'Longest' word has 189,819 letters, takes three hours to pronounce
'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin'.
 
BY BEN LEE
 SHARE
 TWEET
 PIN
 E-MAIL

Latest News
Rita is thrilled when she receives an online friend request from an old friend
Corrie: 6 lessons Rita needs in social networking
15 HOURS AGO
Kym Marsh's Good Morning Britain gaff
Watch Kym Marsh's Good Morning Britain gaffe
18 HOURS AGO
Aussie heroes on Today
Watch 2 Aussies stop robbery, laugh about it on TV
18 HOURS AGO
Ryan Reynolds on The Graham Norton Show
Deadpool's Ryan Reynolds went through puberty at 27
19 HOURS AGO
Shaq plays street-ball
Shaquille O'Neal helps police… win a street game
19 HOURS AGO
A man has been recorded spending more than three hours to pronounce what is supposedly the longest word in the English language.

'Methionylthreonylthreonylglutaminylarginyl...isoleucine' is the chemical name of 'titin' (also known as 'connectin') - the largest known protein. It has 189,819 letters.

**Comment by CreeperLewisCF** [comment]
Hi,

This is not us. This is our username. He is an impersonating!
