### ISSUE TITLE
Can u create compile.php for PHP 5?

### ISSUE THREAD

**Issue by Arkdevnoder** [PEMapModder/HereAuth#22]
Nobody wants install php7 on ubuntu, centos, debian.....
It is very very hard!!

**Comment by PEMapModder** [comment]
Delete the lines that check for PHP 7.0, and replace all occurrences of `... ??` with `... !==null?...:`. For example, replace `$config["name"] ??` with `$config["name"] !== null ? $config["name"] :`.
