### ISSUE TITLE
How to port SimpleAuth data to HereAuth?

### ISSUE THREAD

**Issue by XiangZhao969** [PEMapModder/HereAuth#24]

**Comment by PEMapModder** [comment]
This is being worked on. Duplicate of #1

**Comment by PEMapModder** [comment]
Actually, there are already the basic scripts for them. Written input, still haven't written output.

If you are using MySQL, however, it would be a lot easier.

**Comment by XiangZhao969** [comment]
Could you tell me how to do that, i'm so noob at this

**Comment by PEMapModder** [comment]
This is being worked on. It is just awkward to let you properly specify the paths of the input and output directories.

Please refer to #1 in the future.
