### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Arkdevnoder** [PEMapModder/HereAuth#28]
When i try to register
Warning: file_get_contents(/root/Genisys/plugins/HereAuth/accounts/darkspivel.json): failed to open stream: No such file or directory in phar:///root/Genisys/plugins/HereAuth_Beta.phar/src/HereAuth/Database/Json/JsonSaveDataTask.php on line 46

Warning: zlib_decode(): data error in phar:///root/Genisys/plugins/HereAuth_Beta.phar/src/HereAuth/Database/Json/JsonSaveDataTask.php on line 46

**Comment by PEMapModder** [comment]
Resolved.
