### ISSUE TITLE
Import serverauth's data

### ISSUE THREAD

**Issue by XiangZhao969** [PEMapModder/HereAuth#30]
I'm not using mysql or yaml so how can i import serverauth's data?

**Comment by PEMapModder** [comment]
Then what are you using?

**Comment by XiangZhao969** [comment]
I just use the plugin and players data lay in folder plugins :v

**Comment by PEMapModder** [comment]
What? Then it is YAML.

**Comment by XiangZhao969** [comment]
It said "An import task is already in progress!" but i hadn't started any

**Comment by XiangZhao969** [comment]
Help me please

**Comment by PEMapModder** [comment]
It works now.
