### ISSUE TITLE
MySQL small issue

### ISSUE THREAD

**Issue by RekkuzaRage** [PEMapModder/HereAuth#32]
I have been experiencing this bug with MySQL. It doesn't affect the plugin the itself, everything runs perfectly. But this shows up in console everytime a player logins.

Warning: zlib_decode(): data error in phar:///home/dannyg/ctf/plugins/HereAuth_Beta.phar/src/HereAuth/Database/MySQL/MySQLLoadPlayerTask.php on line 47

**Comment by PEMapModder** [comment]
Latest development build?

**Comment by PEMapModder** [comment]
Fixed
