### ISSUE TITLE
Add option to disable prefixes.

### ISSUE THREAD

**Issue by legoboy0215** [PEMapModder/HereAuth#37]
Can you do that? It is quite annoying because even if I set it to "" (Nothing), PureChat does not work.

I modified the source myself, but hope that this appears on GitHub.

**Comment by PEMapModder** [comment]
Do you mean the Appearance.*Nametag options?

**Comment by PEMapModder** [comment]
I guess the reason is that PureChat does the nametag changing _after_ HereAuth. The original ones should be retained, but not the ones after.
I'll try.

**Comment by legoboy0215** [comment]
Thanks. Should I add it into my weird PR?

**Comment by PEMapModder** [comment]
Add what? The way to fix this is quite complicated.

**Comment by legoboy0215** [comment]
Add option to disable it. Or maybe actually fix it. Event priorities?

**Comment by PEMapModder** [comment]
There is always the possibility that there is another event handler before it.
Please help testing.

**Comment by legoboy0215** [comment]
Eh... Now?

**Comment by PEMapModder** [comment]
@legoboy0215 ?

**Comment by legoboy0215** [comment]
Nothing ;) Using Specter.

**Comment by PEMapModder** [comment]
Put a comment here if it is fixed.

**Comment by legoboy0215** [comment]
IDK. I can't test now. Some tests resulted:

``` php
/**
     * @param PlayerJoinEvent $event
     * @priority HIGHEST
     */ 
    public function onJoin(PlayerJoinEvent $event){
        var_dump($event->getPlayer()->getNameTag());
    }
```

Returns the PureChat nametag, but on anything below the priority it  returns only the HereAuth prepend and appended nametag.

**Comment by PEMapModder** [comment]
That's right. Isn't it OK now?

Also, in case you aren't aware, there is a `MONITOR` priority, but you shouldn't call set**\* at the `MONITOR` priority.

**Comment by legoboy0215** [comment]
IK.
