### ISSUE TITLE
ServerAuth to HereAuth transfer error

### ISSUE THREAD

**Issue by XFuryMCPE** [PEMapModder/HereAuth#48]
Warning: file_put_contents(/home/Network/PvP/PvPLand/plugins/HereAuth/accounts/plugins/serverauth/users/aslan232323.json): failed to open stream: No such file or directory in phar:///home/Network/PvP/PvPLand/plugins/HereAuth_Dev.phar/src/HereAuth/Importer/Writer/JSONAccountWriter.php on line 67

**Comment by SOF3** [comment]
Seems like the AccountReader is giving wrong account names. which account reader are you using?

**Comment by SOF3** [comment]
Please check if the issue has been fixed.

**Comment by XFuryMCPE** [comment]
Why did you answer 6 months later, lmfao, I learned how to make my own plugins already 😂😂😂

**Comment by SOF3** [comment]
"I learned how to make my own plugins already" and "I learned how to make **good** plugins already" are slightly different :wink:

**Comment by XFuryMCPE** [comment]
Are you assuming my work is bad..?

**Comment by SOF3** [comment]
@XFuryMCPE not assuming. I just didn't see any good plugins from your GitHub repo. I do not deny the possibility that you have the ability but did not display them on your GitHub.

**Comment by XFuryMCPE** [comment]
K

**Comment by SOF3** [comment]
But back to the issue itself, please check if the issue has really been fixed.
