### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by ghost** [PEMapModder/HereAuth#52]
We were introduced HereAuth, but you get the following error.
How will this be able to avoid, or improve it?
(Using Google Translate)

[Server thread/ERROR]: Could not load 'D:\PMMP\Genisys\plugins\HereAuth_Beta.phar' in folder 'D:\PMMP\Genisys\plugins\': internal corruption of phar "D:\PMMP\Genisys\plugins\HereAuth_Beta.phar" (__HALT_COMPILER(); not found)

 [Server thread/CRITICAL]: _UnexpectedValueException_: "internal corruption of phar "D:\PMMP\Genisys\plugins\HereAuth_Beta.phar" (__HALT_COMPILER(); not found)" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 85

**Comment by legoboy0215** [comment]
It is better to recompile it yourself.

**Comment by ghost** [comment]
@legoboy0215
Ok, let's try. Thank you for your reply. :)
Should you this Issue is closed? Or it is better that this issue is closed from to solve?

**Comment by legoboy0215** [comment]
No just don't do anything. Post any more issues here :)
BTW, you will have to use the compile script that comes with HereAuth. There is no plugin.yml so don't try to run from source or compile it with devtools.

**Comment by SOF3** [comment]
You downloaded the build wrongly, or you downloaded a corrupted build.

**Comment by ghost** [comment]
OK, Thank you!!
