### ISSUE TITLE
Password displays in Chat

### ISSUE THREAD

**Issue by JoRa22** [PEMapModder/HereAuth#54]
I am having an issue where players can log in but the login message does not display and when they type their password it is displayed in the chat.. 
This happened all of a sudden without me making any changes because it was working just fine until today.. I checked the settings just in case and everything looked good. I have BlockPasswordChat set to True, but it still displays the password when logging in.

What can be causing this issue and can somebody please help me solve it?

Thank you in advance..

**Comment by SzczepanPolska** [comment]
I have the same problem on 0.15

**Comment by SOF3** [comment]
The plugin isn't loaded at all.

**Comment by robske110** [comment]
lol

**Comment by ItzRadius** [comment]
This is Genisys updating. Just wait for an update on HereAuth. In the meantime you can use an alternative like SimpleAuth. It still works fine.

**Comment by SOF3** [comment]
@ItzRadius then wait forever. Unless @iksaku is going to update this plugin (while most of the rest of his _own_ work are outdated), this plugin will never receive an update.

**Comment by legoboy0215** [comment]
@ItzRadius You only need to change 2 lines of code to get the damn plugin working again.

**Comment by SOF3** [comment]
@legoboy0215 which two?

**Comment by legoboy0215** [comment]
See https://github.com/PEMapModder/HereAuth/pull/55/files

**Comment by ItzRadius** [comment]
@legoboy0215 Wow just 2 lines lmao! upload the updated plugin on your github LegoBoy. I'm too lazy to change the 2 lines.
