### ISSUE TITLE
Add limits number of registrations from CID, please

### ISSUE THREAD

**Issue by lowingly** [PEMapModder/HereAuth#57]
In China, every family network IP often changes. It uses dynamic IP.
 "limits number of registrations from an IP" is not useful in China.
I hope you can add "limited number of registrations per device (Customer IDentity)"
Thanks~o(^▽^)o

**Comment by SOF3** [comment]
Any data sent from the device other than IP address can be easily changed through mods.

**Comment by Shock95** [comment]
true.
