### ISSUE TITLE
ServerAuth registrations to HereAuth?

### ISSUE THREAD

**Issue by austina1212** [PEMapModder/HereAuth#58]
Hello? Is there a way to to convert our registered players on serverauth to hereauth? I would really hope so because serverauth is really buggy! If you can help please reply bellow!

**Comment by legoboy0215** [comment]
You should look at the import command. Or something like that lol

Yes, there is a way, and I can prove it works since I did that for my server :)

**Comment by SOF3** [comment]
@legoboy0215 this issue should be closed.
