### ISSUE TITLE
AutoLogin in config.yml is not working

### ISSUE THREAD

**Issue by FaanMaario** [PEMapModder/HereAuth#59]
Hi,
I wanted to say that your plugin is amazing !

But, a little problem is here; the AutoLogin on my config.yml is set to "true" but it's not working.
Is it a bug? How to fix it?
(I use HereAuth-dev.phar)

Thanks for answering :)

**Comment by SOF3** [comment]
1. Define "not working".
2. There doesn't exist something called "AutoLogin". There only exists "AutoAuth", which is about automatically authenticating players according to specific information. AFAIK it works.

Every development build is also called `HereAuth-Dev.phar`. Please check the build number in the plugin version shown when the plugin is loaded (server start).

**Comment by FaanMaario** [comment]
@SOF3
Okay, so this is the AutoAuth; it's not working because when I enabled it, everyone who connect to my server with the same ip have to type their password again, and again (even if they enable it with /opt ai on ect..)
Oh yeah , I forgot to add that this is the last Development build wich is 228 :)

Sorry for this ^^'

**Comment by bmlui** [comment]
Turn on UUID auth. I haven't gotten secret Id auth to work.

**Comment by Ishannaik** [comment]
yep uuid works
