### ISSUE TITLE
IP auth?

### ISSUE THREAD

**Issue by jeffreyvarga** [PEMapModder/HereAuth#67]
I would love it if you could update this plugin so it could have IP auth like broken lens or leet!

**Comment by SOF3** [comment]
This feature already exists.

**Comment by jeffreyvarga** [comment]
So if i use this plugin, and someone registers a account and then they join with the same ip they do not have to type in pass? And if they change ip they type it in?

**Comment by SOF3** [comment]
Please read the `config.yml`. If the features written in the config don't work, open another proper issue, professionally.
