### ISSUE TITLE
HereAuth password glitch

### ISSUE THREAD

**Issue by HipsterAF** [PEMapModder/HereAuth#76]
i didn't change anything, HereAuth was working fine earlier, but now when the server restarts and when people put in the password, it shows on chat, because the "Please login" message doesn't appear when they login, it appears after sometime, i also have 'BlockPasswordChat' on true, and plugin shows no error or get disabled, there's no lag, and there's around 150k json user files in users, i am using pocketmine latest, php 7.0.15, using HereAuth Beta, please help asap
- is it due to php 7.0.15? or because there's too many JSON files to read?

**Comment by SOF3** [comment]
Double check if the plugin is disabled. Show console log if possible.

**Comment by HipsterAF** [comment]
I did, it works only after certain amount of time, before that you dont get "please login" message

**Comment by SOF3** [comment]
Certain amount of time after what? Player join or server start?

And, how long?

**Comment by HipsterAF** [comment]
At player join, when they join together after restart, they dont get the "please login by typing your password in the chat" message idk for how long, so they can use all the commands and even chat without logging in.

**Comment by SOF3** [comment]
I think I know why. I'll check later.

**Comment by HipsterAF** [comment]
Please fix soon.

**Comment by SOF3** [comment]
@HipsterAF Are you using MySQL? How many async workers have you got?

**Comment by SOF3** [comment]
Probably fixed in fcd5ee4.

**Comment by HipsterAF** [comment]
No @SOF3 , using JSON

**Comment by HipsterAF** [comment]
Even /unreg and other processing commands are slow

**Comment by Muqsit** [comment]
@HipsterAF They aren't slow. They are executed asynchronously, which is good.

**Comment by HipsterAF** [comment]
I didnt mean it like that, i meant with my situation they get too laggy sometimes

**Comment by SOF3** [comment]
@HipsterAF can you further elaborate what is "laggy"?
How many async-workers you are using as in pocketmine.yml?
And, please use the latest master build and see if it is fixed.

**Comment by HipsterAF** [comment]
@SOF3 it runs after certain amount of time, and 2 async-workers, and ok i'll check, should i change async-workers to auto?

**Comment by robske110** [comment]
@HipsterAF How many cores does your CPU have?

**Comment by HipsterAF** [comment]
Many, its a dedi 32 gb ram, so should be like 8 or something, will changing it to auto, increase or decrease lag?

**Comment by SOF3** [comment]
@HipsterAF First of all tell us how the latest master build or password_hash build is working.

**Comment by HipsterAF** [comment]
Idk i switched to SimpleAuth​

**Comment by SOF3** [comment]
-_-
