### ISSUE TITLE
import accounts from simpleauth?

### ISSUE THREAD

**Issue by XDqrkneZ** [PEMapModder/HereAuth#78]
### Issue description

 how do you import simpleauth accounts to this? 

### Steps to reproduce the issue

1. ...  how do you transfer simpleauth accounts to hereauth?
2. ...

### OS and versions

haversion:
``` 
 HereAuth v1.0-Dev#39, PharPluginLoader?crc32=d9ea6e22, OS linux, PHP 7.0.3, PM UG9ja2V0TWluZS1NUA== 1.6.2dev-165, API 3.0.0-ALPHA5, MC v1.1.0.55, protocol 113, metadata eyJidWlsZGVyIjoiUG9nZ2l0Q0lcLzEuMC1iZXRhIG5vd2hlcmVcLzIuMCIsImJ1aWxkVGltZSI6IjIwMTctMDYtMDVUMDU6Mzk6NTIrMDAwMCIsInBvZ2dpdEJ1aWxkSWQiOjI0MDQyLCJwcm9qZWN0QnVpbGROdW1iZXIiOjM5LCJjbGFzcyI6IkRldiJ9

```

HereAuth/config.yml:
```yaml I haven't changed anything in config.yml
```
I haven't changed anything in config.yml

### Crashdump, backtrace or other files

* ...

**Comment by legoboy0215** [comment]
/import ,overwrite simpleauth-yaml ,i <path to SimpleAuth data folder>

Not an issue, so closing.
