### ISSUE TITLE
Can't Compile Plugin

### ISSUE THREAD

**Issue by MasterOfTheRealm** [PEMapModder/HereAuth#79]
PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /root/HereAuth-master/compile.php:98

When i try run compile.php

**Comment by MasterOfTheRealm** [comment]
nvm ...my bad

**Comment by SOF3** [comment]
Just visit the [Poggit-CI](https://poggit.pmmp.io/ci/PEMapModder/HereAuth/~) page ;)

**Comment by MasterOfTheRealm** [comment]
Oh no @SOF3 I need HereAuth for a software that uses old protocol packets. Anyways....nailed it xD. Solved the problems with my php bin.
