### ISSUE TITLE
Update to 3.0.0-ALPHA7

### ISSUE THREAD

**Issue by dries-c** [PEMapModder/HereAuth#80]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

haversion:
```
```

HereAuth/config.yml:
```yaml
```

### Crashdump, backtrace or other files

* ...

**Comment by SOF3** [comment]
Anyone interested in making a PR?

**Comment by xXSirGamesXx** [comment]
I have a working HEreAuth but i have to upload everything first.

**Comment by xXSirGamesXx** [comment]
Check my pr

**Comment by SOF3** [comment]
Don't comment on this issue. You may reference this issue in your PR.
